# Generated by Django 4.2.21 on 2025-05-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default=1, upload_to='places/'),
            preserve_default=False,
        ),
    ]
