# Generated by Django 4.2.11 on 2025-05-22 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='movies.movie'),
        ),
    ]
