# Generated by Django 4.2.21 on 2025-05-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_image_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.FloatField(default=2.5),
        ),
    ]
