# Generated by Django 4.2.11 on 2025-05-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='place',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tourroute',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprefer',
            name='created_at',
        ),
    ]
