# Generated by Django 4.2.21 on 2025-05-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='features/alt_image.png', upload_to='places/'),
        ),
    ]
