# Generated by Django 4.2.21 on 2025-05-23 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.place'),
        ),
    ]
