# Generated by Django 4.2.21 on 2025-05-25 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_favorite_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tourroute",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="tourroute",
            name="user",
        ),
        migrations.AddField(
            model_name="routeplace",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="routeplace",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tourroute",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 5, 25, 4, 30, 7, 756430, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tourroute",
            name="total_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tourroute",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tourroute",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
